### ISSUE TITLE
[Suggestion] Option to save to clipboard

### ISSUE THREAD

**Issue by cocoaaa** [FutureMillennium/Screenshot-YouTube#4]
Hi, thank you for creating this useful extension.
I'm curious if I can change the save setting to save it to the clipboard instead of downloading it to the default chrome's download location. 

I often need to put the screenshot in Keynote/PPT slide and it would be really useful if I can bypass the intermediate steps of copy-pasting the downloaded image to the slides. 

Thank you!

**Comment by roxaloxa** [comment]
Seconding this!

**Comment by naturallymitchell** [comment]
👍💖

**Comment by FutureMillennium** [comment]
Added in version 2.3.0, thanks to @roxaloxa.

**Comment by cocoaaa** [comment]
wow, thanks a lot!

**Comment by l1bbcsg** [comment]
This had the immediate effect of breaking the extension for all current users and producing a concerning warning.
<img width="451" alt="Screenshot 2020-02-04 at 22 06 09" src="https://user-images.githubusercontent.com/1044684/73756753-b080fb00-479a-11ea-8d73-612e0fdb581e.png">
Perhaps this could have been handled better.

**Comment by FutureMillennium** [comment]
This should be fixed in version 2.3.2. I've removed the clipboardWrite permission, as it doesn't seem to be necessary.

**Comment by roxaloxa** [comment]
having to click "accept new permissions" is hardly **breaking** an extension, but regardless, turns out that permission was unnecessary so apologies for including that. first time messing with extension stuff. 😓

**Comment by FutureMillennium** [comment]
I agree with @roxaloxa, though I do wish Chrome's warning wasn't so misleading & poorly worded – you can hardly “modify” any data since you can't read anything, and what's wrong with copying to the clipboard anyway? – and that their documentation was better.

The permission is “recommended” for extensions yet you still get this awful treatment anyway.

![image](https://user-images.githubusercontent.com/7760353/73837638-2bd1c380-4812-11ea-8815-35e3eef93201.png)
